#pragma once

#include "../type/frame-sprite.h"
#include "pebble.h"

#if defined(PBL_PLATFORM_EMERY) || defined(PBL_PLATFORM_GABBRO)
#define BATTERY_BAR_BASE_SPRITE_H 111
#define BATTERY_BAR_EXTENDED_SPRITE_H 39
#define BATTERY_BAR_SPRITE_W 39
#define BATTERY_BOTTOM_SPRITE_H 12
#define BATTERY_BOTTOM_SPRITE_W 39
#define BATTERY_TOP_SPRITE_H 45
#define BATTERY_TOP_SPRITE_W 39
#define BOTTOM_PANEL_INDICATOR_SPRITE_H 45
#define BOTTOM_PANEL_INDICATOR_SPRITE_W 24
#define BOTTOM_PANEL_LEFT_BRACE_SPRITE_W 22
#define BOTTOM_PANEL_MIDDLE_SPRITE_H 45
#define BOTTOM_PANEL_MIDDLE_SPRITE_W 18
#define BOTTOM_PANEL_RIGHT_BRACE_SPRITE_H 57
#define BOTTOM_PANEL_RIGHT_BRACE_SPRITE_W 38
#define BOTTOM_PANNEL_LEFT_BRACE_SPRITE_H 60
#define MAIN_BOARD_SPRITE_H 117
#define MAIN_BOARD_SPRITE_W 129
#define TIME_BOARD_SPRITE_H 111
#define TIME_BOARD_SPRITE_W 66
#else
#define BATTERY_BAR_BASE_SPRITE_H 76
#define BATTERY_BAR_EXTENDED_SPRITE_H 20
#define BATTERY_BAR_SPRITE_W 26
#define BATTERY_BOTTOM_SPRITE_H 8
#define BATTERY_BOTTOM_SPRITE_W 26
#define BATTERY_TOP_SPRITE_H 30
#define BATTERY_TOP_SPRITE_W 26
#define BOTTOM_PANEL_INDICATOR_SPRITE_H 30
#define BOTTOM_PANEL_INDICATOR_SPRITE_W 16
#define BOTTOM_PANEL_LEFT_BRACE_SPRITE_W 15
#define BOTTOM_PANEL_MIDDLE_SPRITE_H 30
#define BOTTOM_PANEL_MIDDLE_SPRITE_W 12
#define BOTTOM_PANEL_RIGHT_BRACE_SPRITE_H 38
#define BOTTOM_PANEL_RIGHT_BRACE_SPRITE_W 25
#define BOTTOM_PANNEL_LEFT_BRACE_SPRITE_H 40
#define MAIN_BOARD_SPRITE_H 80
#define MAIN_BOARD_SPRITE_W 94
#define TIME_BOARD_SPRITE_H 76
#define TIME_BOARD_SPRITE_W 48
#endif

void frame_sprites_init(bool use_health);
void frame_sprites_deinit(void);
void frame_sprites_lazy_battery_init(void);
void frame_sprites_update_indicator(bool use_health);
void frame_sprite_alloc(GBitmap **part_bitmap, enum FrameSprite part);
