#pragma once

enum FrameSprite
{
    FRAME_SPRITE_MAIN_BOARD,
    FRAME_SPRITE_TIME_BOARD,
    FRAME_SPRITE_BOTTOM_BOARD_INDICATOR,
    FRAME_SPRITE_BOTTOM_BOARD_LEFT_BRACE,
    FRAME_SPRITE_BOTTOM_BOARD_MIDDLE,
    FRAME_SPRITE_BOTTOM_BOARD_RIGHT_BRACE,
    FRAME_SPRITE_TIME_ARROW,
    FRAME_SPRITE_BATTERY_TOP,
    FRAME_SPRITE_BATTERY_BAR_BASE,
    FRAME_SPRITE_BATTERY_BAR_EXTENDED,
    FRAME_SPRITE_BATTERY_BOTTOM,
    FRAME_SPRITE_COUNT,
};